######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 22 19:12:29 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += common.h shader.h triangle.h vector.h
SOURCES += common.cpp main.cpp shader.cpp triangle.cpp vector.cpp
